### ISSUE TITLE
regression_test.py import error

### ISSUE THREAD

**Issue by zhangli3000** [ToniRV/spark_vio_evaluation#42]
**Description:**
regression_test.py can not import the function run_dataset

**Command:**
```
./evaluation/regression_tests.py -r -a --plot --save_plots --save_boxplots --save_results ../regress_ev.yaml
```

**Console output:**
```
Traceback (most recent call last):                              
  File "./evaluation/regression_tests.py", line 13, in <module> 
    from evaluation.evaluation_lib import run_dataset           
ImportError: cannot import name run_dataset                     

```

**Additional files:**
Please attach all the files needed to reproduce the error.

Please give also the following information:
* evo version: https://github.com/ToniRV/evo-1
* Python version used:python2.7
* operating system and version (e.g. Ubuntu 16.04 or Windows 10): Ubuntu18.04
* did you change the source code? (yes / no):no
```

executable_path: '../Kimera-VIO/buil/stereoVIOEuroc'                
vocabulary_path: '../Kimera-VIO/vocabulary/ORBvoc.yml'              
results_dir: 'Kimera-VIO-Evaluation/results'             
params_dir: '../Kimera-VIO/params/Euroc'                            
dataset_dir: '../Kimera-VIO/script/euroc'                            
regression_tests_dir: 'Kimera-VIO-Evaluation/regression_tests'                                                                                                 
                                                                                                      
datasets_to_run:                                                                                      
 - name: V1_01_easy                                                                                   
   use_lcd: false                                                                                     
   plot_vio_and_pgo: true                                                                             
   segments: [1]                                                                                      
   pipelines: ['S']                                                                                   
   discard_n_start_poses: 10                                                                          
   discard_n_end_poses: 10                                                                            
   initial_frame: 10                                                                                  
   final_frame: 22000                                                                                 
   parallel_run: true                                                                                 


```
